# Generated by Django 4.1.3 on 2022-12-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_remove_userprofile_manager_userprofile_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='manager',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='Керівник'),
        ),
    ]
