# Generated by Django 4.1.3 on 2022-12-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_userprofile_manager_userprofile_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='manager',
            new_name='supervisor',
        ),
    ]
