# Generated by Django 4.1.3 on 2022-12-09 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_rename_manager_userprofile_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of', to='userprofile.userprofile', verbose_name='Керівник'),
        ),
    ]
