# Generated by Django 4.1.3 on 2022-12-30 13:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_code', models.CharField(default=None, max_length=23)),
                ('req_date', models.DateTimeField(auto_now=True, verbose_name='Дата заявки')),
                ('pay_date', models.DateField(default=datetime.datetime(2023, 1, 2, 13, 47, 55, 986071, tzinfo=datetime.timezone.utc), help_text='<sup>план</sup>', verbose_name='Дата потреби')),
                ('target', models.TextField(max_length=500, verbose_name='Ціль')),
                ('sum', models.IntegerField(default=0, verbose_name='Сума')),
                ('receiver', models.CharField(max_length=50, verbose_name='Отримувач')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Готово для підпису')),
                ('is_agreed', models.BooleanField(default=False, verbose_name='Узгоджено')),
                ('info_text', models.CharField(blank=True, max_length=500, verbose_name='Дод інфо')),
                ('doc', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='reqs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'ЗаявкиРДС',
                'ordering': ['-req_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, max_length=500, verbose_name='Повідомлення')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата повідомлення')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='requestApp.req')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор повідомлення')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Agreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата узгодження')),
                ('req', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requestApp.req')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Узгодив')),
            ],
            options={
                'verbose_name': 'Узгодження',
                'verbose_name_plural': 'Узгодження',
                'ordering': ['-date'],
            },
        ),
    ]
