# Generated by Django 4.1.3 on 2022-11-24 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('pay_date', models.DateField(auto_now_add=True, verbose_name='Дата потреби')),
                ('target', models.CharField(max_length=500, verbose_name='Ціль')),
                ('sum', models.IntegerField(default=0, verbose_name='Сума')),
                ('info_text', models.CharField(blank=True, max_length=500, verbose_name='Дод інфо')),
                ('receiver', models.CharField(max_length=50, verbose_name='Отримувач')),
                ('code', models.CharField(default='1', max_length=23, verbose_name='Код')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Готово для підпису')),
                ('is_agreed', models.BooleanField(default=False, verbose_name='Узгоджено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
