# Generated by Django 4.1.3 on 2022-11-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='author',
        ),
    ]
