# Generated by Django 4.1.3 on 2022-12-30 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 13, 48, 36, 492466, tzinfo=datetime.timezone.utc), help_text='<sup>план</sup>', verbose_name='Дата потреби'),
        ),
    ]
