# Generated by Django 4.1.3 on 2022-11-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0004_alter_request_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['req_date'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'ЗаявкиРДС'},
        ),
        migrations.CreateModel(
            name='Agreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата узгодження')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requestApp.request')),
            ],
            options={
                'verbose_name': 'Узгодження',
                'verbose_name_plural': 'Узгодження',
                'ordering': ['-date'],
            },
        ),
    ]
