# Generated by Django 4.1.3 on 2022-11-24 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestApp', '0007_alter_request_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreed',
            name='auth',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Узгодив'),
        ),
    ]
