# Generated by Django 4.1.3 on 2022-11-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0009_alter_agreed_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreed',
            name='comment',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
