# Generated by Django 4.1.3 on 2022-11-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0010_agreed_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-req_date'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'ЗаявкиРДС'},
        ),
        migrations.AlterField(
            model_name='agreed',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='request',
            name='target',
            field=models.TextField(max_length=500, verbose_name='Ціль'),
        ),
    ]
