# Generated by Django 4.1.3 on 2022-11-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0011_alter_request_options_alter_agreed_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pay_date',
            field=models.DateField(verbose_name='Дата потреби'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата заявки'),
        ),
    ]
