# Generated by Django 4.1.3 on 2022-12-01 14:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestApp', '0013_remove_request_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Req',
        ),
    ]
