# Generated by Django 4.1.3 on 2022-12-01 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0014_rename_request_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 20, 45, 47, 215946), verbose_name='Дата потреби'),
        ),
    ]
