# Generated by Django 4.1.3 on 2022-12-01 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0015_alter_req_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 20, 52, 56, 771241), verbose_name='Дата потреби'),
        ),
        migrations.AlterField(
            model_name='req',
            name='target',
            field=models.TextField(error_messages={'blank': 'Необхідно заповнити це поле'}, max_length=500, verbose_name='Ціль'),
        ),
    ]
