# Generated by Django 4.1.3 on 2022-12-02 15:08

from django.db import migrations, models
import requestApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0016_alter_req_pay_date_alter_req_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreed',
            old_name='auth',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='req',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='req',
            name='pay_date',
            field=models.DateField(default=requestApp.models.get_default_pay_date, help_text='<sup>Запланована дата оплати</sup>', validators=[requestApp.models.validate_pay_date], verbose_name='Дата потреби'),
        ),
    ]
