# Generated by Django 4.1.3 on 2022-12-02 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestApp', '0017_rename_auth_agreed_user_rename_author_req_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreed',
            old_name='request',
            new_name='req',
        ),
        migrations.RemoveField(
            model_name='agreed',
            name='comment',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, max_length=500, verbose_name='Ціль')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата повідомлення')),
                ('answer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestApp.message')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestApp.req')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор повідомлення')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ['-date'],
            },
        ),
    ]
