# Generated by Django 4.1.3 on 2022-12-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0018_rename_request_agreed_req_remove_agreed_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='requestApp.message'),
        ),
    ]
