# Generated by Django 4.1.3 on 2022-12-06 10:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('requestApp', '0020_alter_message_answer_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(blank=True, choices=[('DIRECTOR', 'Директор'), ('MANAGER', 'Керівник')], default=None, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='answer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestApp.message', verbose_name='Відповідь на:'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(blank=True, max_length=500, verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='agreed',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='requestApp.user', verbose_name='Узгодив'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='requestApp.user', verbose_name='Автор повідомлення'),
        ),
        migrations.AlterField(
            model_name='req',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='requestApp.user', verbose_name='Автор'),
        ),
    ]
