# Generated by Django 4.1.3 on 2022-12-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0022_remove_message_answer_to_alter_agreed_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='photo_doc',
            field=models.ImageField(blank=True, upload_to='images/users', verbose_name='фото документ'),
        ),
    ]
