# Generated by Django 4.1.3 on 2022-12-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_department_code'),
        ('requestApp', '0023_req_photo_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='Автор'),
        ),
    ]
