# Generated by Django 4.1.3 on 2022-12-09 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import requestApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestApp', '0025_alter_req_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='pay_date',
            field=models.DateField(default=requestApp.models.get_default_pay_date, help_text='<sup>план</sup>', verbose_name='Дата потреби'),
        ),
        migrations.AlterField(
            model_name='req',
            name='photo_doc',
            field=models.ImageField(blank=True, upload_to='images/users', verbose_name='фото документів'),
        ),
        migrations.AlterField(
            model_name='req',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='reqs', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
