# Generated by Django 4.1.3 on 2022-12-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0027_alter_message_req_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='photo_doc',
        ),
    ]
